# Generated by Django 4.2.7 on 2023-11-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_talk', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
